name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build test runner
      run: make test-runner

    - name: Tests
      run: |
        make basics-tests
        make git-tests
        make java-tests